import { ChangeEvent, Component, FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './modal.css';
import './layout.css';
import './csv.css';
import './auth.css';
import './notifications.css';
import { request } from './client';
import cashflowMark from './assets/cashflow-mark.png';

type Lang = 'en' | 'es';
type User = { id: string; email: string; displayName: string; role: string; active: boolean };
type Account = { id: string; name: string; type: string; active: boolean };
type Category = { id: string; name: string; direction: string; active: boolean };
type Movement = { id: string; direction: string; amountMinor: number; currency: string; description: string; occurredOn: string; status: string };
type DeletionRequest = { id: string; entityType: string; entityId: string; requestedBy: string; status: string; createdAt: string };
type Tab = 'record' | 'movements' | 'accounts' | 'categories' | 'analytics' | 'users' | 'requests';
const APP_VERSION = '0.1.0';

const copy = {
  en: { loading:'Loading local storage…', setup:'Local CashFlow setup', email:'Email', password:'Password', name:'Display name', signIn:'Sign in', signOut:'Sign out', recovery:'Save your recovery code', recoveryHelp:'Store this code in a password manager. It will not be shown again.', saved:'I saved it', record:'Record movement', movements:'Movements', accounts:'Accounts', categories:'Categories', analytics:'Analytics', add:'Add', save:'Save', edit:'Edit', deactivate:'Deactivate', accountName:'Account name', categoryName:'Category name', noAccounts:'No active accounts yet.', noCategories:'No active categories yet.', amount:'Amount', currency:'Currency', date:'Date', description:'Description', type:'Type', status:'Status', income:'Income', expense:'Expense', active:'Active', voided:'Voided', void:'Void', show:'Show amounts', hide:'Hide amounts', savedNotice:'Saved successfully.', voidedNotice:'Movement voided.', deactivatedNotice:'Item deactivated.', year:'Year', topIncome:'Month with most income', topExpense:'Month with most expenses', monthlyIncome:'Average monthly income', noData:'No active movements for this year.' },
  es: { loading:'Cargando almacenamiento local…', setup:'Configuración local de CashFlow', email:'Correo electrónico', password:'Contraseña', name:'Nombre visible', signIn:'Ingresar', signOut:'Cerrar sesión', recovery:'Guardá tu código de recuperación', recoveryHelp:'Guardalo en un administrador de contraseñas. No se mostrará nuevamente.', saved:'Ya lo guardé', record:'Registrar movimiento', movements:'Movimientos', accounts:'Cuentas', categories:'Categorías', analytics:'Analítica', add:'Agregar', save:'Guardar', edit:'Editar', deactivate:'Desactivar', accountName:'Nombre de cuenta', categoryName:'Nombre de categoría', noAccounts:'Todavía no hay cuentas activas.', noCategories:'Todavía no hay categorías activas.', amount:'Monto', currency:'Moneda', date:'Fecha', description:'Descripción', type:'Tipo', status:'Estado', income:'Ingreso', expense:'Egreso', active:'Activo', voided:'Anulado', void:'Anular', show:'Mostrar montos', hide:'Ocultar montos', savedNotice:'Guardado correctamente.', voidedNotice:'Movimiento anulado.', deactivatedNotice:'Elemento desactivado.', year:'Año', topIncome:'Mes con más ingresos', topExpense:'Mes con más egresos', monthlyIncome:'Promedio mensual de ingresos', noData:'No hay movimientos activos para este año.' }
} as const;
type Copy = Record<keyof typeof copy.en, string>;

class ErrorBoundary extends Component<{children:ReactNode},{error:string}> {
  state={error:''}; static getDerivedStateFromError(error:Error){return {error:error.message||'Unexpected application error'};}
  render(){return this.state.error?<main className="card"><h1>CashFlow could not continue</h1><p className="error">{this.state.error}</p></main>:this.props.children;}
}
function Language({language,setLanguage}:{language:Lang;setLanguage:(v:Lang)=>void}) { return <select className="language" aria-label="Language" value={language} onChange={e=>setLanguage(e.target.value as Lang)}><option value="es">ES</option><option value="en">EN</option></select>; }
function Brand(){return <div className="brand"><img src={cashflowMark} alt="CashFlow"/><div><strong>CashFlow</strong><span>Control your money, clearly.</span></div></div>;}
function RuntimeMeta(){const [meta,setMeta]=useState({version:APP_VERSION,mode:window.cashflow?'Desktop · Local SQLite':'Web development · Local SQLite'});useEffect(()=>{window.cashflow?.runtime?.().then(value=>setMeta({version:value.version,mode:value.mode}));},[]);return <p className="runtime-meta">v{meta.version} · {meta.mode}</p>;}
function App(){
  const [language,setLanguage]=useState<Lang>('es'), [initialized,setInitialized]=useState<boolean|null>(null), [token,setToken]=useState(''), [user,setUser]=useState<User|null>(null), [recovery,setRecovery]=useState(''), [error,setError]=useState('');
  const t=copy[language];
  useEffect(()=>{request<{initialized:boolean}>('/v1/setup').then(v=>setInitialized(v.initialized)).catch(e=>setError(e.message));},[]);
  if(error)return <main><h1>CashFlow</h1><p className="error">{error}</p></main>;
  if(initialized===null)return <main>{t.loading}</main>;
  if(recovery)return <main className="card"><Language language={language} setLanguage={setLanguage}/><h1>{t.recovery}</h1><p>{t.recoveryHelp}</p><code>{recovery}</code><button onClick={()=>{setRecovery('');setInitialized(true);}}>{t.saved}</button></main>;
  if(!initialized)return <Setup t={t} language={language} setLanguage={setLanguage} done={setRecovery}/>;
  if(!token||!user)return <Login t={t} language={language} setLanguage={setLanguage} success={(nextToken,nextUser)=>{setToken(nextToken);setUser(nextUser);}}/>;
  return <Dashboard token={token} user={user} language={language} setLanguage={setLanguage} logout={()=>{request('/v1/auth/logout',token,'POST').finally(()=>{setToken('');setUser(null);});}}/>;
}
function Setup({t,language,setLanguage,done}:{t:Copy;language:Lang;setLanguage:(v:Lang)=>void;done:(v:string)=>void}){
  const [email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
  const submit=async(e:FormEvent)=>{e.preventDefault();try{const r=await request<{recovery_code:string}>('/v1/setup/initialize',undefined,'POST',{email,displayName:name,password});done(r.recovery_code);}catch(x){setError((x as Error).message);}};
  return <main className="auth-shell"><section className="auth-card"><div className="auth-topbar"><Language language={language} setLanguage={setLanguage}/><RuntimeMeta/></div><Brand/><h1>{t.setup}</h1><p>Storage: Local SQLite</p><form onSubmit={submit}><input placeholder={t.email} value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder={t.name} value={name} onChange={e=>setName(e.target.value)} required/><input type="password" placeholder="Password (12+ characters)" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Create administrator</button>{error&&<p className="error">{error}</p>}</form></section></main>;
}
function Login({t,language,setLanguage,success}:{t:Copy;language:Lang;setLanguage:(v:Lang)=>void;success:(token:string,user:User)=>void}){
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
  const submit=async(e:FormEvent)=>{e.preventDefault();try{const r=await request<{token:string;user:User}>('/v1/auth/login',undefined,'POST',{email,password});success(r.token,r.user);}catch(x){setError((x as Error).message);}};
  return <main className="auth-shell"><section className="auth-card"><div className="auth-topbar"><Language language={language} setLanguage={setLanguage}/><RuntimeMeta/></div><Brand/><div className="auth-copy"><h1>{language==='es'?'Bienvenido nuevamente':'Welcome back'}</h1><p>{language==='es'?'Ingresá para continuar administrando tu flujo de caja.':'Sign in to continue managing your cash flow.'}</p></div><form onSubmit={submit}><input placeholder={t.email} value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder={t.password} value={password} onChange={e=>setPassword(e.target.value)} required/><button>{t.signIn}</button>{error&&<p className="error">{error}</p>}</form></section></main>;
}
function Amount({amount,currency,hidden}:{amount:number;currency?:string;hidden:boolean}){return <>{hidden?'•••••':(amount/100).toFixed(2)}{currency ? ` ${currency}` : ''}</>;}
function currentLocalDate(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;}
function formatAmount(value:string){const cleaned=value.replace(/[^\d,]/g,'');const [rawWhole,...rawDecimals]=cleaned.split(',');if(!rawWhole&&!rawDecimals.length)return '';const whole=(rawWhole||'0').replace(/^0+(?=\d)/,'');const grouped=whole.replace(/\B(?=(\d{3})+(?!\d))/g,'.');return rawDecimals.length?`${grouped},${rawDecimals.join('').slice(0,2)}`:grouped;}
function MoneyInput({placeholder}:{placeholder:string}){const [display,setDisplay]=useState('');return <><input className="money-value" aria-label={placeholder} inputMode="decimal" placeholder="$0,00" value={display ? `$${display}` : ''} onChange={e=>setDisplay(formatAmount(e.target.value))} required/><input name="amount" type="hidden" value={display.replace(/\./g,'').replace(',','.')} /></>;}
function downloadCSV(name:string, content:string){const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);}
function exportTimestamp(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}_${String(now.getHours()).padStart(2,'0')}-${String(now.getMinutes()).padStart(2,'0')}-${String(now.getSeconds()).padStart(2,'0')}`;}
const categoryTemplateCSV='name,direction\nOffice supplies,expense\n';
const movementTemplateCSV='account_name,category_name,direction,amount_minor,currency,description,occurred_on\nCash,Office supplies,expense,125000,ARS,Printer supplies,2026-08-22\n';
function parseCSV(content:string, expected:string[]){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let index=0;index<content.length;index+=1){const char=content[index],next=content[index+1];if(char==='"'&&quoted&&next==='"'){cell+='"';index+=1;}else if(char==='"'){quoted=!quoted;}else if(char===','&&!quoted){row.push(cell.trim());cell='';}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')index+=1;row.push(cell.trim());if(row.some(value=>value!==''))rows.push(row);row=[];cell='';}else{cell+=char;}}if(cell||row.length){row.push(cell.trim());rows.push(row);}if(rows.length<2||rows[0].join(',')!==expected.join(','))throw new Error(`CSV must use: ${expected.join(',')}`);if(rows.slice(1).some(values=>values.length!==expected.length))throw new Error('CSV contains a row with an invalid number of columns.');return rows.slice(1);}
function Dashboard({token,user,language,setLanguage,logout}:{token:string;user:User;language:Lang;setLanguage:(v:Lang)=>void;logout:()=>void}){
  const t=copy[language], [tab,setTab]=useState<Tab>('record'),[accounts,setAccounts]=useState<Account[]>([]),[categories,setCategories]=useState<Category[]>([]),[movements,setMovements]=useState<Movement[]>([]),[users,setUsers]=useState<User[]>([]),[requests,setRequests]=useState<DeletionRequest[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[hidden,setHidden]=useState(true),[pendingAction,setPendingAction]=useState<{kind:'accounts'|'categories'|'transactions'|'users';id:string;action:'deactivate'|'void'|'delete'}|null>(null);
  const load=async()=>{try{const [a,c,m]=await Promise.all([request<Account[]>('/v1/accounts',token),request<Category[]>('/v1/categories',token),request<Movement[]>('/v1/transactions',token)]);setAccounts(a??[]);setCategories(c??[]);setMovements(m??[]);if(user.role==='administrator')setUsers(await request<User[]>('/v1/users',token));if(user.role==='administrator'||user.role==='manager')setRequests(await request<DeletionRequest[]>('/v1/deletion-requests',token));}catch(e){setError((e as Error).message);}};
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(!notice&&!error)return;const timer=window.setTimeout(()=>{setNotice('');setError('');},10_000);return()=>window.clearTimeout(timer);},[notice,error]);
  const post=(path:string,body:(f:FormData)=>unknown,message=t.savedNotice)=>async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;setError('');try{await request(path,token,'POST',body(new FormData(form)));form.reset();await load();setNotice(message);}catch(x){setError((x as Error).message);}};
  const edit=async(kind:'accounts'|'categories',item:Account|Category)=>{const name=window.prompt(language==='es'?'Nombre':'Name',item.name);if(!name?.trim())return;const current='type'in item?item.type:item.direction;const value=window.prompt(kind==='accounts'?'cash | bank | wallet':'income | expense | both',current);if(!value)return;try{await request(`/v1/${kind}/${item.id}`,token,'PUT',kind==='accounts'?{name,type:value}:{name,direction:value});await load();setNotice(t.savedNotice);}catch(x){setError((x as Error).message);}};
  const deactivate=(kind:'accounts'|'categories',id:string)=>setPendingAction({kind,id,action:'deactivate'});
  const requestVoid=(id:string)=>setPendingAction({kind:'transactions',id,action:'void'});
  const userAction=(id:string,action:'deactivate'|'delete')=>setPendingAction({kind:'users',id,action});
  const confirmAction=async()=>{if(!pendingAction)return;try{const {kind,id,action}=pendingAction;if(kind==='transactions'){await request(`/v1/transactions/${id}/void`,token,'POST');setNotice(user.role==='operator'?(language==='es'?'Solicitud de anulación enviada.':'Void request submitted.'):t.voidedNotice);}else if(kind==='users'){await request(`/v1/users/${id}${action==='deactivate'?'/deactivate':''}`,token,action==='delete'?'DELETE':'POST');setNotice(action==='delete'?(language==='es'?'Usuario eliminado.':'User deleted.'):(language==='es'?'Usuario desactivado.':'User deactivated.'));}else{await request(`/v1/${kind}/${id}/deactivate`,token,'POST');setNotice(t.deactivatedNotice);}await load();}catch(x){setError((x as Error).message);}finally{setPendingAction(null);}};
  const resolveRequest=async(id:string,decision:'approve'|'reject')=>{try{await request(`/v1/deletion-requests/${id}/${decision}`,token,'POST');await load();setNotice(t.savedNotice);}catch(x){setError((x as Error).message);}};
  const exportCSV=async(path:string,name:string)=>{try{downloadCSV(name,await request<string>(path,token));}catch(x){setError((x as Error).message);}};
  const importCategoriesCSV=async(file:File)=>{try{const rows=parseCSV(await file.text(),['name','direction']);for(const [name,direction] of rows)await request('/v1/categories',token,'POST',{name,direction});await load();setNotice(t.savedNotice);}catch(x){setError((x as Error).message);}};
  const importMovementsCSV=async(file:File)=>{try{const rows=parseCSV(await file.text(),['account_name','category_name','direction','amount_minor','currency','description','occurred_on']);const accountIDs=new Map(accounts.map(item=>[item.name,item.id]));const categoryIDs=new Map(categories.map(item=>[item.name,item.id]));for(const row of rows){const [,,direction]=row;const categoryName=row[1];if(categoryName&&!categoryIDs.has(categoryName)){try{await request('/v1/categories',token,'POST',{name:categoryName,direction});}catch(error){if(!(error instanceof Error)||!error.message.includes('UNIQUE constraint failed: categories.name'))throw error;}categoryIDs.set(categoryName,'');}}const latestCategories=await request<Category[]>('/v1/categories',token);latestCategories.forEach(item=>categoryIDs.set(item.name,item.id));const values=rows.map((row,index)=>{const amountMinor=Number(row[3]);if(!Number.isSafeInteger(amountMinor)||amountMinor<=0)throw new Error(`Row ${index+2}: amount_minor must be a positive integer.`);const accountId=accountIDs.get(row[0]);if(!accountId)throw new Error(`Row ${index+2}: account ${row[0]} does not exist.`);const categoryId=row[1]?categoryIDs.get(row[1]):'';if(row[1]&&!categoryId)throw new Error(`Row ${index+2}: category ${row[1]} could not be created.`);return {accountId,categoryId,direction:row[2],amountMinor,currency:row[4].toUpperCase(),description:row[5],occurredOn:row[6]};});for(const value of values)await request('/v1/transactions',token,'POST',value);await load();setNotice(t.savedNotice);}catch(x){setError((x as Error).message);}};
  const labels:Record<Tab,string>={record:t.record,movements:t.movements,accounts:t.accounts,categories:t.categories,analytics:t.analytics,users:language==='es'?'Usuarios':'Users',requests:language==='es'?'Solicitudes':'Requests'};
  const availableTabs=(Object.keys(labels) as Tab[]).filter(k=>user.role!=='operator'||k==='record'||k==='movements'||k==='categories').filter(k=>user.role==='administrator'||k!=='users');
  return <main><header><div><h1>CashFlow</h1><small>{user.displayName} · {user.role}</small></div><div className="header-actions"><Language language={language} setLanguage={setLanguage}/><button onClick={logout}>{t.signOut}</button></div></header><nav className="tabs">{availableTabs.map(k=><button key={k} className={tab===k?'selected':''} onClick={()=>setTab(k)}>{labels[k]}</button>)}</nav>{error&&<p className="error">{error}</p>}{notice&&<p className="notice">{notice}</p>}
  {tab==='record'&&<section className="card record-card"><h2>{t.record}</h2><form className="transaction" onSubmit={post('/v1/transactions',f=>({accountId:f.get('accountId'),categoryId:f.get('categoryId'),direction:f.get('direction'),amountMinor:Math.round(Number(f.get('amount'))*100),currency:String(f.get('currency')).toUpperCase(),description:f.get('description'),occurredOn:f.get('occurredOn')}))}><select className="transaction-account" name="accountId" required><option value="">{t.accounts}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select className="transaction-category" name="categoryId"><option value="">{t.categories}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="transaction-direction" name="direction"><option value="expense">{t.expense}</option><option value="income">{t.income}</option></select><MoneyInput placeholder={t.amount}/><select className="transaction-currency" name="currency" defaultValue="ARS" aria-label={t.currency}><option value="ARS">ARS · Peso argentino</option><option value="USD">USD · US dollar</option><option value="EUR">EUR · Euro</option><option value="BRL">BRL · Real brasileño</option></select><input className="transaction-date" name="occurredOn" type="date" defaultValue={currentLocalDate()} aria-label={t.date} required/><input className="transaction-description" name="description" placeholder={t.description} required/><button className="transaction-save">{t.save}</button></form></section>}
  {tab==='movements'&&<section className="card"><div className="section-head"><h2>{t.movements}</h2><button className="secondary" onClick={()=>setHidden(!hidden)}>◉ {hidden?t.show:t.hide}</button></div><CsvActions onTemplate={()=>downloadCSV('cashflow-movements-template.csv',movementTemplateCSV)} onImport={importMovementsCSV} onExport={user.role==='operator'?undefined:()=>exportCSV('/v1/exports/transactions.csv',`cashflow-movements-${exportTimestamp()}.csv`)}/><table><thead><tr><th>{t.date}</th><th>{t.type}</th><th>{t.currency}</th><th>{t.amount}</th><th>{t.description}</th><th>{t.status}</th><th/></tr></thead><tbody>{movements.map(m=><tr key={m.id} className={m.status==='voided'?'voided-row':''}><td>{m.occurredOn}</td><td>{m.direction==='income'?t.income:t.expense}</td><td>{m.currency}</td><td><Amount amount={m.amountMinor} hidden={hidden}/></td><td>{m.description}</td><td>{m.status==='active'?t.active:t.voided}</td><td>{m.status==='active'&&<button className="secondary" onClick={()=>requestVoid(m.id)}>{user.role==='operator'?(language==='es'?'Solicitar anulación':'Request void'):t.void}</button>}</td></tr>)}</tbody></table></section>}
  {tab==='accounts'&&<Management t={t} kind="accounts" items={accounts} submit={post('/v1/accounts',f=>({name:f.get('name'),type:f.get('type')}))} edit={v=>edit('accounts',v)} deactivate={id=>deactivate('accounts',id)}/>}
  {tab==='categories'&&user.role==='operator'&&<section className="card"><h2>{t.categories}</h2><form className="inline" onSubmit={post('/v1/categories',f=>({name:f.get('name'),direction:f.get('direction')}))}><input name="name" placeholder={t.categoryName} required/><select name="direction"><option value="expense">{t.expense}</option><option value="income">{t.income}</option><option value="both">Both</option></select><button>{t.add}</button></form></section>}
  {tab==='categories'&&user.role!=='operator'&&<Management t={t} kind="categories" items={categories} submit={post('/v1/categories',f=>({name:f.get('name'),direction:f.get('direction')}))} edit={v=>edit('categories',v)} deactivate={id=>deactivate('categories',id)} csv={{onTemplate:()=>downloadCSV('cashflow-categories-template.csv',categoryTemplateCSV),onImport:importCategoriesCSV}}/>}
  {tab==='analytics'&&<Analytics t={t} movements={movements} hidden={hidden}/>} 
  {tab==='users'&&user.role==='administrator'&&<UserManagement users={users} currentUserId={user.id} submit={post('/v1/users',f=>({email:f.get('email'),displayName:f.get('displayName'),password:f.get('password'),role:f.get('role')}))} onAction={userAction} language={language}/>} 
  {tab==='requests'&&user.role!=='operator'&&<DeletionRequests requests={requests} resolve={resolveRequest} language={language}/>} 
  {pendingAction&&<div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-action-title"><h2 id="confirm-action-title">{pendingAction.action==='void'?(language==='es'?'¿Confirmar anulación?':'Confirm void?'):pendingAction.action==='delete'?(language==='es'?'¿Eliminar este usuario?':'Delete this user?'):(language==='es'?'¿Desactivar este elemento?':'Deactivate this item?')}</h2><p>{pendingAction.action==='void'?(user.role==='operator'?(language==='es'?'Se creará una solicitud para que un administrador o gestor la apruebe.':'A request will be created for an administrator or manager to approve.'):(language==='es'?'El movimiento quedará anulado y se conservará en el historial.':'The movement will be voided and retained in history.')):pendingAction.action==='delete'?(language==='es'?'La eliminación es permanente. Los usuarios con actividad registrada deben desactivarse para preservar la auditoría.':'Deletion is permanent. Users with recorded activity must be deactivated to preserve the audit trail.'):(language==='es'?'Dejará de estar disponible para nuevas cargas. El historial existente se conserva.':'It will no longer be available for new movements. Existing history is retained.')}</p><div className="modal-actions"><button className="secondary" onClick={()=>setPendingAction(null)}>{language==='es'?'Cancelar':'Cancel'}</button><button onClick={confirmAction}>{pendingAction.action==='void'?(language==='es'?'Confirmar':'Confirm'):pendingAction.action==='delete'?(language==='es'?'Eliminar':'Delete'):(language==='es'?'Desactivar':'Deactivate')}</button></div></section></div>}
  </main>;
}
function CsvActions({onTemplate,onImport,onExport}:{onTemplate:()=>void;onImport:(file:File)=>void;onExport?:()=>void}){const selectFile=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(file)onImport(file);event.target.value='';};return <div className="csv-actions"><button className="secondary" onClick={onTemplate}>Download template</button><label className="secondary file-action">Import CSV<input type="file" accept=".csv,text/csv" onChange={selectFile}/></label>{onExport&&<button className="secondary" onClick={onExport}>Export CSV</button>}</div>;}
function Management({t,kind,items,submit,edit,deactivate,csv}:{t:Copy;kind:'accounts'|'categories';items:(Account|Category)[];submit:(e:FormEvent<HTMLFormElement>)=>void;edit:(v:Account|Category)=>void;deactivate:(id:string)=>void;csv?:{onTemplate:()=>void;onImport:(file:File)=>void}}) {
  const accounts = kind === 'accounts';
  return <section className="card"><h2>{accounts ? t.accounts : t.categories}</h2><form className="inline" onSubmit={submit}><input name="name" placeholder={accounts ? t.accountName : t.categoryName} required/><select name={accounts ? 'type' : 'direction'}>{accounts ? <><option value="cash">Cash</option><option value="bank">Bank</option><option value="wallet">Wallet</option></> : <><option value="expense">{t.expense}</option><option value="income">{t.income}</option><option value="both">Both</option></>}</select><button>{t.add}</button></form>{csv&&<CsvActions {...csv}/>} {items.length ? <ul className="management-list">{items.map(item => <li key={item.id}><span>{item.name} <small>{'type' in item ? item.type : item.direction}</small></span><span><button className="secondary" onClick={() => edit(item)}>{t.edit}</button><button className="secondary" onClick={() => deactivate(item.id)}>{t.deactivate}</button></span></li>)}</ul> : <p className="items">{accounts ? t.noAccounts : t.noCategories}</p>}</section>;
}
function UserManagement({users,currentUserId,submit,onAction,language}:{users:User[];currentUserId:string;submit:(event:FormEvent<HTMLFormElement>)=>void;onAction:(id:string,action:'deactivate'|'delete')=>void;language:Lang}){return <section className="card"><h2>{language==='es'?'Usuarios':'Users'}</h2><form className="inline" onSubmit={submit}><input name="displayName" placeholder={language==='es'?'Nombre':'Name'} required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder={language==='es'?'Contraseña (12+ caracteres)':'Password (12+ characters)'} required/><select name="role"><option value="operator">{language==='es'?'Operador':'Operator'}</option><option value="manager">{language==='es'?'Gestor':'Manager'}</option><option value="administrator">{language==='es'?'Administrador':'Administrator'}</option></select><button>{language==='es'?'Crear usuario':'Create user'}</button></form><ul className="management-list">{users.map(item=><li key={item.id} className={item.active?'':'voided-row'}><span>{item.displayName}<small> {item.email} · {item.role} · {item.active?(language==='es'?'activo':'active'):(language==='es'?'inactivo':'inactive')}</small></span>{item.id!==currentUserId&&<span>{item.active&&<button className="secondary" onClick={()=>onAction(item.id,'deactivate')}>{language==='es'?'Desactivar':'Deactivate'}</button>}<button className="secondary" onClick={()=>onAction(item.id,'delete')}>{language==='es'?'Eliminar':'Delete'}</button></span>}</li>)}</ul></section>;}
function DeletionRequests({requests,resolve,language}:{requests:DeletionRequest[];resolve:(id:string,decision:'approve'|'reject')=>void;language:Lang}){const pending=requests.filter(item=>item.status==='pending');return <section className="card"><h2>{language==='es'?'Solicitudes de anulación':'Void requests'}</h2>{pending.length?<ul className="management-list">{pending.map(item=><li key={item.id}><span>{language==='es'?'Movimiento':'Movement'} <small>{item.entityId}</small></span><span><button onClick={()=>resolve(item.id,'approve')}>{language==='es'?'Aprobar':'Approve'}</button><button className="secondary" onClick={()=>resolve(item.id,'reject')}>{language==='es'?'Rechazar':'Reject'}</button></span></li>)}</ul>:<p className="items">{language==='es'?'No hay solicitudes pendientes.':'No pending requests.'}</p>}</section>;}
function Analytics({t,movements,hidden}:{t:Copy;movements:Movement[];hidden:boolean}){const [year,setYear]=useState(String(new Date().getFullYear()));const stats=useMemo(()=>{const data=new Map<string,{month:string;currency:string;income:number;expense:number}>();movements.filter(m=>m.status==='active'&&m.occurredOn.startsWith(year)).forEach(m=>{const key=`${m.occurredOn.slice(0,7)}-${m.currency}`,current=data.get(key)??{month:m.occurredOn.slice(0,7),currency:m.currency,income:0,expense:0};current[m.direction==='income'?'income':'expense']+=m.amountMinor;data.set(key,current);});return [...data.values()];},[movements,year]);if(!stats.length)return <section className="card"><div className="section-head"><h2>{t.analytics}</h2><label>{t.year} <input value={year} maxLength={4} onChange={e=>setYear(e.target.value)}/></label></div><p>{t.noData}</p></section>;const income=stats.reduce((a,b)=>a.income>b.income?a:b),expense=stats.reduce((a,b)=>a.expense>b.expense?a:b),averages=Object.entries(stats.reduce<Record<string,{total:number;months:number}>>((a,v)=>{const x=a[v.currency]??{total:0,months:0};x.total+=v.income;x.months++;a[v.currency]=x;return a;},{}));return <section className="card"><div className="section-head"><h2>{t.analytics}</h2><label>{t.year} <input value={year} maxLength={4} onChange={e=>setYear(e.target.value)}/></label></div><div className="summary"><strong>{t.topIncome}: {income.month} · <Amount amount={income.income} currency={income.currency} hidden={hidden}/></strong><strong>{t.topExpense}: {expense.month} · <Amount amount={expense.expense} currency={expense.currency} hidden={hidden}/></strong>{averages.map(([currency,v])=><strong key={currency}>{t.monthlyIncome} ({currency}): <Amount amount={Math.round(v.total/v.months)} currency={currency} hidden={hidden}/></strong>)}</div></section>;}
createRoot(document.getElementById('root')!).render(<ErrorBoundary><App/></ErrorBoundary>);
